build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run --standard=.phpcs.xml

filter:
  excluded_paths:
    - ".devcontainer/*"
    - ".init/*"
    - ".testcontainer/*"
    - ".vscode/*"
    - "bench/*"
    - "bin/*"
    - "tests/*"
    - "vendor/*"
