# This docker-compose file is to run tests on Docker.
version: "3.7"

services:
  test:
    build:
      context: .
      dockerfile: ./.testcontainer/Dockerfile
      args:
        - NAME_IMAGE=php:8.0.0-cli-alpine
    environment:
      - COVERALLS_REPO_TOKEN
    volumes:
      - ./composer.json:/app/composer.json
      - ./.git/:/app/.git
      - ./src:/app/src
      - ./tests:/app/tests
      - ./report:/app/report
      - ./bin:/app/bin
  dev:
    build:
      context: .
      dockerfile: ./.testcontainer/Dockerfile
      args:
        - NAME_IMAGE=php:8.0.0-cli-alpine
    environment:
      - COVERALLS_REPO_TOKEN
    volumes:
      - .:/app
